[package]
name = "shared"
version = "0.0.0"
authors = ["Confio Team"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "2.0.3"
cosmwasm-schema = "2.0.3"
thiserror = "1.0.61"
anyhow = "1.0.86"
cw2 = "2.0.0"
serde = "1.0.202"
serde_json = "1.0.117"
cw-utils = "2.0.0"
